### PR TITLE
adding support for react 16.0.0

### PR DESCRIPTION
**Pull request by DonGiulio**
I didn't manage to `npm run test`, I was getting: 
 
     Cannot find module 'react/lib/ReactComponentTreeHook' from 'ReactDebugTool.js'

hope this works.

### CODE REVIEW

**Comment by JamieDixon** [comment]
Thanks for doing this @DonGiulio. I appreciate you taking the time.

There's a few more adjustments that need making before the tests will pass:

1) Upgrade React to V16 `npm i react@16.0.0 --save-dev`
2) Upgrade react-dom to V16 `npm i react-dom@16.0.0 --save-dev`
3) Upgrade react-test-renderer to V16 `npm i react-test-renderer@16.0.0 --save-dev`
4) Modify the react `peerDependency` version a bit (`>= 0.14`).

With these changes I think we'll be good to merge this. 👍

**Comment by DonGiulio** [comment]
Hello, 

I did the modifications, the CI seems to be passing, 

any more changes? 

Thanks,

**Comment by DonGiulio** [comment]
sorry actually it’s not passing.

**Comment by JamieDixon** [comment]
Can you please revasectis branch with upstream? Let me know if you need help doing that. It should pass CI once it’s up to date.

**Comment by JamieDixon** [comment]
Rebase this branch*

**Comment by DonGiulio** [comment]
I’m not sure what you mean by revasectis?

**Comment by JamieDixon** [comment]
Sorry, I’m on my phone and it all went a bit wrong. I meant to say “please can you rebase this branch with upstream master”. 😄

**Comment by JamieDixon** [comment]
Thanks @DonGiulio. This is looking great. I've merged it this morning and it will be part of the next release 👌

**Comment by JamieDixon** [comment]
@DonGiulio Your changes are now in version 3.0.0 https://www.npmjs.com/package/react-lifecycle-component

Thank you for the time you put into helping out, it's really appreciated. 🍾 🎉

**Comment by DonGiulio** [comment]
well… I’ve not really done much,  thank you for the open source library, that one is the impressive bit.

**Pull request merged**
