### PR TITLE
fix prop types check

### PR DESCRIPTION
**Pull request by thecotne**
related to https://github.com/facebook/react/issues/12453

screen shot 2018-12-25 at 12 36 48 pm

### CODE REVIEW

**Comment by jessepinho** [comment]
@JamieDixon could we get this merged? I'm currently getting this error when passing a `React.memo`-wrapped component to `connectWithLifecycle`.

**Comment by JamieDixon** [comment]
@thecotne This is great. Thanks for making this adjustment and for linking to the original issue.

@jessepinho I'll merge this today and publish a patch version to npm.

**Comment by jessepinho** [comment]
@JamieDixon Thanks so much! <3

**Comment by JamieDixon** [comment]
@jessepinho 2.0.6 published https://www.npmjs.com/package/react-lifecycle-component

**Pull request merged**
